import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "The Check",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="w-full  m-auto">{children}</main>;
}
